version: 3.8
services:
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo-data:
